version: "3"
services:
  nodered:
    container_name: nodered
    image: nodered/node-red:1.1.3
    volumes:
      - "./nodered:/data:rw"
    environment: 
      - TZ=Asia/Makassar
    ports:
      - 1880:1880